version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      DATABASE_HOST: 172.17.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d usersDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  etl:
      container_name: etl-pipeline_container
      restart: always
      image: etl-pipeline
      command: python3 main.py
      volumes:
        - .:/app
      depends_on:
        db:
          condition: service_healthy
      stdin_open: true
      tty: true

